# The sequence of triangle numbers is generated by adding the natural numbers. 
# So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. 
# The first ten terms would be:
# 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
# Let us list the factors of the first seven triangle numbers:
"""
 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
"""
t = 0
k = []

    

while True:
    #while loop
    t+=1
    #add 1 to t until 
    a = int(t*(t+1)/2)
    # calculate a with the fomula
    for i in range(1,a+1):
        if a % i == 0:
            k.append(i)
            # if a could be divided by i, add to list k
    if len(k) > 500:
        print(f'the factors of the first seven triangle numebrs is {a}')
        print(k)
        break
    k = []

